#---------------------------------#
#      general configuration      #
#---------------------------------#

environment:
  nuget_api_key:
    secure: jGqjs4k5xaMCD0tVCbMeGAY7n91+CAytsDj6HrmCLwjgHMSrAZZotIUdmaEUK+45

# version format
version: 0.2.{build}

# clone directory
clone_folder: c:\projects\VL.PJLink

branches:
  only:
    - master

only_commits:
  message: /build/

install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

#---------------------------------#
#       build configuration       #
#---------------------------------#

build: off

# after_build:

#---------------------------------#
#       Deployment                #
#---------------------------------#

deploy_script:
  - nuget pack VL.PJLink.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - nuget setApiKey %nuget_api_key%
  - nuget push C:\projects\VL.PJLink\VL.PJLink.%APPVEYOR_BUILD_VERSION%.nupkg -Source https://api.nuget.org/v3/index.json
    
artifacts:
  - path: '*.nupkg'
    type: NuGetPackage
  
#---------------------------------#
#         notifications           #
#---------------------------------#

test: off

notifications:

  # Email
  - provider: Email
    to:
      - sebl@schnellebuntebilder.de
    subject: 'VL.PJLink Build {{status}}'  # optional
    message: "%APPVEYOR_BUILD_VERSION% @commit {{commitId}} has been triggered for build. Exited with status: {{status}}."    # optional
    on_build_status_changed: true